# Help if we get any PORT 80 already is use error
# Run the below commands to check if anybody is using the default PORT 80
# docker-compose down  # Stop container on current dir if there is a docker-compose.yml
# docker rm -fv $(docker ps -aq)  # Remove all containers
# sudo lsof -i -P -n | grep <port number>  # List who's using the port

# For cleaning up docker-compose containers, RUN the below commands for a clean build:
# docker-compose rm
# docker-compose build --no-cache
# docker-compose up -d --force-recreate

version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  auth:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./auth
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./auth:/app
